In [1]:
# Time series forecasting is a technique to predict events through a sequence of time.
# Forecasting involves taking historical data and using them to predict the future.
# Time series forecasting including weather forecasting, earthquake prediction, etc.
# The model observes the trend of the past events and use them to predict the new event.

In [2]:
import numpy as np

X = np.array(([1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]), dtype=float)
y = np.array(([0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0]), dtype=float)
lr = 0.5

In [3]:
class Recurrent_Neural_Network():
    def __init__(self):
        self.input = 5
        self.output = 5
        self.hidden = 10
        self.W1 = np.random.randn(self.input, self.hidden)
        self.W2 = np.random.randn(self.hidden, self.output)

    def forward(self, X):
        # difference with bpnn is rnn feedback/loop each neuron when input is given
        data = []
        data.append(np.array(X))
        res = 0
        for i in range(0, len(X)):
            self.z = np.dot(data[0], self.W1)
            self.z2 = self.sigmoid(self.z)
            self.z3 = np.dot(self.z2, self.W2) 
            res = self.sigmoid(self.z3)
            data.append(res)
        return data[len(data)-1]

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def der_sigmoid(self, s):
        return s * (1 - s)

    def backward(self, X, y, z):
        self.z_error = y - z
        self.z_delta = self.z_error * self.der_sigmoid(z)

        self.z2_error = self.z_delta.dot(self.W2.T)
        self.z2_delta = self.z2_error * self.der_sigmoid(self.z2)

        self.W1 += lr * X.T.dot(self.z2_delta)
        self.W2 += lr * self.z2.T.dot(self.z_delta)

    def train (self, X, y):
        res = self.forward(X)
        self.backward(X, y, res)

In [4]:
epoch = 1000
NN = Recurrent_Neural_Network()
for _ in range(epoch):
    print("Input: \n", X)
    print("Target: \n", y) 
    print("Predicted Output: \n", NN.forward(X))
    print("Loss: ", np.mean(np.square(y - NN.forward(X))))
    print("\n")
    NN.train(X, y)

Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.7321952  0.83836599 0.5216946  0.82052253 0.40454271]
 [0.64757259 0.63064668 0.65610243 0.75032055 0.72256296]
 [0.67301955 0.57269637 0.602688   0.7351355  0.53898172]
 [0.670548   0.63803391 0.71767874 0.74655127 0.72260978]
 [0.39415397 0.86968463 0.4931641  0.64600607 0.54302888]]
Loss:  0.3712572086568857


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.6112031  0.75062094 0.38652105 0.70893517 0.27874826]
 [0.50976617 0.47784815 0.53273737 0.616238   0.60275112]
 [0.55640539 0.43668153 0.48281589 0.62316671 0.41599629]
 [0.54460272 0.48244249 0.59649599 0.61112751 0.61758754]
 [0.298

 [[0.15468223 0.77308478 0.13988769 0.14277464 0.02831421]
 [0.06092842 0.12125361 0.65137361 0.17910143 0.18183585]
 [0.17625869 0.10586446 0.21370761 0.67434782 0.08628846]
 [0.20664261 0.05592776 0.21413738 0.10251552 0.74202515]
 [0.6514739  0.17076102 0.05524611 0.1400349  0.16293058]]
Loss:  0.03565165729776194


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.15246477 0.77567097 0.13865205 0.14084396 0.02781751]
 [0.05916412 0.12034416 0.65656693 0.17718865 0.17974237]
 [0.17387408 0.10461924 0.21139945 0.67908565 0.08517165]
 [0.20417553 0.05525833 0.21155778 0.10084407 0.74507613]
 [0.65760538 0.16904602 0.05397823 0.13927587 0.16161467]]
Loss:  0.034721559470515216


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1

 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.08820035 0.85059179 0.09536741 0.08376024 0.01562796]
 [0.02188665 0.08774981 0.80506942 0.11136286 0.11418594]
 [0.10413088 0.06564716 0.12782605 0.81316148 0.05508047]
 [0.12315328 0.03726962 0.12828503 0.05565409 0.83826557]
 [0.81301942 0.11705035 0.02412035 0.10388663 0.11184816]]
Loss:  0.012892956620375531


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.08747971 0.85151756 0.09478886 0.0830946  0.01550636]
 [0.0215962  0.08727866 0.80673121 0.11052227 0.11335712]
 [0.10331309 0.06516655 0.12675461 0.81468245 0.05474532]
 [0.12215371 0.03706944 0.12725688 0.05517341 0.83942791]
 [0.8146446  0.1163682  0.02385694 0.10330128 0.11112382]]
Loss:  0.012698509960765684


Input: 
 [[1. 0. 0. 0. 0.

Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.06309718 0.88539042 0.07364427 0.06033677 0.01153582]
 [0.01313979 0.06911188 0.86257895 0.08117297 0.08376021]
 [0.07489362 0.04829849 0.09004927 0.86664802 0.04309021]
 [0.08749017 0.030155   0.09155284 0.03928964 0.88091255]
 [0.86912832 0.09060956 0.0158952  0.0801743  0.08390043]]
Loss:  0.006846838886951837


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.06277907 0.88587046 0.07334583 0.06003823 0.01148594]
 [0.0130461  0.0688425  0.86330096 0.08078027 0.08335448]
 [0.07451353 0.04807118 0.08956984 0.86733199 0.0429325 ]
 [0.08702927 0.03006244 0.09107753 0.03908789 0.88148162]
 [0.8

Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.05006565 0.90600626 0.06084626 0.04812642 0.00953791]
 [0.00962198 0.05727957 0.89197381 0.06492803 0.06676705]
 [0.05916463 0.03886253 0.07054745 0.89475733 0.03644549]
 [0.06851724 0.02629236 0.07197116 0.03116031 0.90476947]
 [0.897885   0.07422678 0.01240561 0.06498943 0.06717702]]
Loss:  0.004359695121168841


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.04989055 0.90629707 0.06066575 0.04796287 0.00951174]
 [0.00957902 0.05710899 0.89236613 0.06470769 0.06653387]
 [0.05895139 0.0387342  0.07028793 0.89513602 0.03635321]
 [0.06826158 0.0262393  0.07170702 0.03105304 0.90509719]
 [0.8

Predicted Output: 
 [[0.04167302 0.92036792 0.05191268 0.04031428 0.00830606]
 [0.0076837  0.04874267 0.91069342 0.05431057 0.05546982]
 [0.04890922 0.03267596 0.0582105  0.9129171  0.03190726]
 [0.05627722 0.02370161 0.05931064 0.02608013 0.92065739]
 [0.91621543 0.06256389 0.01044505 0.05419488 0.05569435]]
Loss:  0.0030263264417265743


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.04156545 0.9205576  0.05179429 0.04021453 0.00829058]
 [0.00766041 0.04862842 0.91093224 0.05417373 0.05532355]
 [0.04877743 0.03259624 0.05805381 0.91314986 0.03184738]
 [0.05612072 0.02366767 0.05914852 0.02601582 0.92086321]
 [0.91644908 0.06240874 0.0104214  0.05405184 0.05554409]]
Loss:  0.0030106875125195014


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 

Loss:  0.00240142683712803


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.03706911 0.9286088  0.04675466 0.03605469 0.00765111]
 [0.00672051 0.04374484 0.92088733 0.04843696 0.0491837 ]
 [0.04326718 0.02925677 0.05154128 0.92287261 0.02929882]
 [0.04959673 0.02222714 0.0523835  0.02334557 0.92950576]
 [0.92617778 0.05580172 0.00946686 0.04797942 0.04920609]]
Loss:  0.002391137470652241


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.03699068 0.92875134 0.04666514 0.03598228 0.00764009]
 [0.00670468 0.04365778 0.92106053 0.04833658 0.04907618]
 [0.04317105 0.0291984  0.05142832 0.92304207 0.02925351]
 [0.04948328 0.02220158 0.05226572

Predicted Output: 
 [[0.03332966 0.93548032 0.04242475 0.03260818 0.00713091]
 [0.00598706 0.03952548 0.92912549 0.04363999 0.04404518]
 [0.03868754 0.02646962 0.04618128 0.93094247 0.02710219]
 [0.04420659 0.02098902 0.04678078 0.0211499  0.93674157]
 [0.93420518 0.05013505 0.00872426 0.04280616 0.0438637 ]]
Loss:  0.0019277629285603904


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.03327095 0.9355894  0.04235576 0.03255416 0.00712283]
 [0.00597588 0.03945813 0.92925452 0.04356448 0.04396433]
 [0.03861571 0.0264258  0.04609755 0.93106898 0.02706707]
 [0.0441223  0.02096922 0.04669305 0.0211156  0.93685543]
 [0.93433068 0.05004494 0.00871298 0.04272419 0.04377943]]
Loss:  0.0019208717848531378


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 

Predicted Output: 
 [[0.03042396 0.94092058 0.03897279 0.02993664 0.00673433]
 [0.00544586 0.036153   0.93549895 0.03989599 0.04003933]
 [0.03513668 0.02429859 0.04205316 0.93719558 0.02533825]
 [0.04004988 0.01999298 0.04244901 0.01945778 0.94238344]
 [0.94039418 0.0456364  0.00818007 0.03872644 0.0396826 ]]
Loss:  0.0016011617403508208


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.03037825 0.9410068  0.03891788 0.02989465 0.00672815]
 [0.00543754 0.03609933 0.935599   0.03983698 0.03997626]
 [0.0350809  0.0242644  0.04198849 0.93729378 0.02531006]
 [0.03998476 0.01997703 0.04238105 0.01943125 0.94247227]
 [0.94049115 0.04556504 0.00817174 0.03866194 0.03961669]]
Loss:  0.001596261654476991


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1

Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.02819797 0.9451416  0.03627735 0.02789234 0.00643516]
 [0.00504746 0.03351778 0.94036339 0.03701794 0.03696689]
 [0.03242413 0.02263233 0.03891289 0.94197133 0.02394807]
 [0.03688936 0.01920376 0.03914716 0.01816845 0.94671101]
 [0.94510168 0.04214188 0.00778302 0.03557607 0.03647056]]
Loss:  0.0013711578047540768


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.02816091 0.94521224 0.0362321  0.02785831 0.00643021]
 [0.00504094 0.03347355 0.94044425 0.03696995 0.03691573]
 [0.03237904 0.02260456 0.03886077 0.94205072 0.02392461]
 [0.03683693 0.01919039 0.03909232 0.01814703 0.94678308]
 [0.

Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.02630975 0.94875409 0.03395729 0.02615856 0.00618456]
 [0.00472005 0.03125023 0.94447616 0.03456998 0.03436074]
 [0.03013031 0.02121664 0.0362643  0.94600975 0.02273912]
 [0.03422772 0.01851196 0.03635987 0.01707851 0.95038192]
 [0.94906876 0.03915058 0.00745996 0.03289362 0.03374534]]
Loss:  0.0011899840638669602


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.02627915 0.94881284 0.03391945 0.02613046 0.00618053]
 [0.00471482 0.03121327 0.94454268 0.03453027 0.03431853]
 [0.03009321 0.02119369 0.0362215  0.94607507 0.02271929]
 [0.03418476 0.01850056 0.03631483 0.01706087 0.95044138]
 [0.

Predicted Output: 
 [[0.02473536 0.95178566 0.03200016 0.02471219 0.00597784]
 [0.00445414 0.02933909 0.9478949  0.03252438 0.03218947]
 [0.02822394 0.02003441 0.03406652 0.94936629 0.02170808]
 [0.03202399 0.01791613 0.03404676 0.01617159 0.95344036]
 [0.95235612 0.03664148 0.00720038 0.03065448 0.03147631]]
Loss:  0.0010487932984209638


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.02470959 0.95183542 0.03196796 0.02468851 0.00597447]
 [0.00444984 0.02930766 0.94795078 0.03249085 0.03215395]
 [0.02819279 0.02001505 0.03403062 0.94942114 0.02169101]
 [0.03198804 0.01790622 0.03400898 0.01615676 0.9534904 ]
 [0.95240977 0.03660031 0.0071962  0.03061783 0.03143921]]
Loss:  0.0010465569756298377


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 

 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.02333192 0.95450082 0.030239   0.02342152 0.00579522]
 [0.00422232 0.02762143 0.95093367 0.03069757 0.0302565 ]
 [0.02653017 0.01897889 0.03211544 0.95234889 0.0207697 ]
 [0.03007282 0.01736768 0.03199414 0.01536397 0.95616325]
 [0.95526943 0.03439637 0.00697655 0.02865995 0.02945882]]
Loss:  0.0009305521168112423


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.02331002 0.95454329 0.03021139 0.02340136 0.00579238]
 [0.00421874 0.02759453 0.95098103 0.03066903 0.03022635]
 [0.02650378 0.0189624  0.03208504 0.95239537 0.0207549 ]
 [0.03004247 0.01735898 0.03196217 0.01535137 0.95620571]
 [0.95531476

 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.02222535 0.95664878 0.02883995 0.02240243 0.00565229]
 [0.00404285 0.02625888 0.95332333 0.0292551  0.02873484]
 [0.02519892 0.01814533 0.03058233 0.9546935  0.02001597]
 [0.02854403 0.01692189 0.03038249 0.01472731 0.95830685]
 [0.95755421 0.03262251 0.00680513 0.02709045 0.02787316]]
Loss:  0.0008424094136971126


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.02220622 0.95668596 0.02881568 0.0223848  0.00564983]
 [0.00403977 0.02623527 0.95336459 0.02923015 0.02870856]
 [0.02517594 0.01813091 0.03055587 0.95473398 0.02000283]
 [0.02851768 0.01691407 0.03035469 0.01471631 0.95834387]
 [0.95759361 0.03259183 0.0068022  0.02706335 0.0278458 ]]
Loss:  0.00084092521721247

Predicted Output: 
 [[0.02125392 0.95853873 0.02760459 0.02150638 0.00552755]
 [0.00388761 0.02505751 0.95541623 0.02798736 0.02740129]
 [0.02403365 0.01741245 0.02924022 0.95674612 0.01934354]
 [0.02720949 0.01651948 0.02897297 0.01416819 0.96018561]
 [0.95955046 0.03106393 0.00665832 0.02571632 0.02648595]]
Loss:  0.0007687385464671676


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.02123703 0.95857161 0.02758306 0.02149079 0.00552539]
 [0.00388493 0.02503659 0.95545256 0.02796531 0.02737813]
 [0.02401342 0.01739971 0.02921692 0.95678175 0.01933176]
 [0.02718635 0.01651238 0.02894852 0.01415847 0.96021823]
 [0.95958507 0.03103684 0.0066558  0.02569248 0.02646189]]
Loss:  0.0007674887714577838


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 

 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.02037756 0.96024649 0.02648474 0.0206966  0.00541557]
 [0.00374935 0.02397013 0.95730004 0.02684265 0.02620045]
 [0.02298541 0.01675028 0.02803242 0.9585929  0.01872777]
 [0.02601199 0.01614652 0.02770592 0.01366338 0.96187755]
 [0.96134324 0.02965784 0.00652881 0.02448075 0.02523918]]
Loss:  0.000705257800907084


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.02036255 0.96027575 0.02646552 0.02068272 0.00541366]
 [0.00374699 0.02395148 0.95733227 0.02682303 0.02617991]
 [0.02296748 0.01673893 0.02801176 0.95862449 0.01871714]
 [0.02599154 0.01614005 0.02768426 0.01365473 0.9619065 ]
 [0.96137388 0.02963376 0.00652662 0.02445962 0.02521787]]
Loss:  0.0007041952224259589


Input: 
 [[1. 0. 0. 0. 0

Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.01958194 0.96179872 0.02546389 0.01996001 0.00531432]
 [0.00362523 0.02298044 0.95900661 0.02580259 0.02511234]
 [0.02203637 0.01614815 0.02693826 0.96026521 0.0181608 ]
 [0.02493038 0.01579889 0.02655952 0.01320454 0.96341085]
 [0.96296389 0.02838201 0.00641363 0.02336317 0.02411175]]
Loss:  0.0006500749728490899


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.01956852 0.96182493 0.02544663 0.01994757 0.00531261]
 [0.00362314 0.02296372 0.95903538 0.02578504 0.025094  ]
 [0.02202038 0.01613798 0.02691982 0.9602934  0.01815116]
 [0.02491218 0.01579294 0.02654021 0.01319679 0.9634367 ]
 [0.

 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.01889192 0.96314599 0.02457551 0.01931992 0.00522679]
 [0.00351862 0.02212053 0.96048368 0.02490001 0.02417047]
 [0.02121545 0.01562511 0.0259911  0.96171203 0.01766266]
 [0.02399681 0.01548975 0.02556842 0.01280601 0.96473827]
 [0.96436382 0.02727667 0.00631554 0.02239774 0.02313786]]
Loss:  0.0006041039450744578


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.01887977 0.9631697  0.02455985 0.01930864 0.00522525]
 [0.00351675 0.02210539 0.96050965 0.02488413 0.02415391]
 [0.02120103 0.01561589 0.02597445 0.96173746 0.01765384]
 [0.02398042 0.01548425 0.02555101 0.012799   0.9647616 ]
 [0.96438841

Loss:  0.0005632241669462163


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.01824392 0.96441179 0.02373886 0.0187176  0.00514479]
 [0.00341934 0.02131196 0.96186811 0.02405199 0.02328769]
 [0.02044648 0.01513314 0.02510311 0.96306755 0.01718919]
 [0.02312406 0.01519242 0.02464048 0.01243115 0.9659826 ]
 [0.96567354 0.02624011 0.00622493 0.02149485 0.02222697]]
Loss:  0.0005625294787754469


Input: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Target: 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Predicted Output: 
 [[0.01823291 0.9644333  0.02372463 0.01870735 0.0051434 ]
 [0.00341766 0.02129822 0.96189161 0.02403757 0.0232727 ]
 [0.02043343 0.01512477 0.02508803 0.96309056 0.01718109]
 [0.02310926 0.01518731 0.02462